### ISSUE TITLE
old key?

### ISSUE THREAD

**Issue by fenwick67** [cabal-club/cabals#2]
per https://github.com/cabal-club/cabal-club.github.io/commit/b8243028f641305f282896c06dace5bab3280805 , isn't the newer key `a1efbe73cb1499e6932b603e0a59341b4399f5c789bd6c5d7746888204265cc2` ?

**Comment by nikolaiwarner** [comment]
yes! really the public community key has been changing so often we should just list it one place... like maybe just on the cabal.chat site

Then over here we document the keys we've used in case someday we invent the technology that can revive them :D

It's time to move to a new key anyhow ... `a1efbe73...` isnt responding anymore
